# Generated by Django 5.2.8 on 2025-11-07 23:41

import django.db.models.deletion
import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(default=players.models.generate_player_number, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('position', models.CharField(choices=[('GS', 'Goal Shooter'), ('GA', 'Goal Attack'), ('WA', 'Wing Attack'), ('C', 'Centre'), ('WD', 'Wing Defence'), ('GD', 'Goal Defence'), ('GK', 'Goal Keeper')], max_length=2)),
                ('photo', models.ImageField(blank=True, default='player_photos/default.jpg', upload_to='player_photos/')),
                ('institution_name', models.CharField(max_length=300)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('consent_given', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='players.player')),
            ],
            options={
                'ordering': ['-registered_date'],
            },
        ),
    ]
