# Generated by Django 5.2.8 on 2025-11-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together={('player', 'tournament')},
        ),
    ]
